var n129 = {
	BRAZIL_MCC: "724",
	BRAZIL_CELLBROADCAST_CHANNEL: 50,
	MOBILE_INFO: {
		brazil: {
			carriers: {
				"00": "NEXTEL",
				"02": "TIM",
				"03": "TIM",
				"04": "TIM",
				"05": "CLARO",
				"06": "VIVO",
				"07": "CTBC",
				"08": "TIM",
				10: "VIVO",
				11: "VIVO",
				15: "SERCOMTEL",
				16: "OI",
				23: "VIVO",
				24: "OI",
				31: "OI",
				32: "CTBC",
				33: "CTBC",
				34: "CTBC",
				37: "AEIOU",
			},
			regions: {
				11: "SP",
				12: "SP",
				13: "SP",
				14: "SP",
				15: "SP",
				16: "SP",
				17: "SP",
				18: "SP",
				19: "SP",
				21: "RJ",
				22: "RJ",
				24: "RJ",
				27: "ES",
				28: "ES",
				31: "MG",
				32: "MG",
				33: "MG",
				34: "MG",
				35: "MG",
				37: "MG",
				38: "MG",
				41: "PR",
				42: "PR",
				43: "PR",
				44: "PR",
				45: "PR",
				46: "PR",
				47: "SC",
				48: "SC",
				49: "SC",
				51: "RS",
				53: "RS",
				54: "RS",
				55: "RS",
				61: "DF",
				62: "GO",
				63: "TO",
				64: "GO",
				65: "MT",
				66: "MT",
				67: "MS",
				68: "AC",
				69: "RO",
				71: "BA",
				73: "BA",
				74: "BA",
				75: "BA",
				77: "BA",
				79: "SE",
				81: "PE",
				82: "AL",
				83: "PB",
				84: "RN",
				85: "CE",
				86: "PI",
				87: "PE",
				88: "CE",
				89: "PI",
				91: "PA",
				92: "AM",
				93: "PA",
				94: "PA",
				95: "RR",
				96: "AP",
				97: "AM",
				98: "MA",
				99: "MA",
			},
		},
	},
	userFacingInfo: function (e) {
		var t = e.voice.network,
			n = e.iccId,
			r = navigator.mozIccManager.getIccById(n),
			o = r ? r.iccInfo : null,
			i = t ? t.shortName || t.longName : null;
		i && o && o.isDisplaySpnRequired && o.spn && (i = o.isDisplayNetworkNameRequired && i !== o.spn ? i + " " + o.spn : o.spn);
		var a, s;
		if (this.isBrazil(e)) {
			var u = e.voice.cell.gsmLocationAreaCode % 100,
				l = this.MOBILE_INFO.brazil.carriers,
				c = this.MOBILE_INFO.brazil.regions;
			(a = l[t.mnc] || this.BRAZIL_MCC + t.mnc), (s = c[u] ? c[u] + " " + u : "");
		}
		return { operator: i, carrier: a, region: s };
	},
	isBrazil: function (e) {
		var t = e.voice.cell,
			n = e.voice.network;
		return n ? n.mcc === this.BRAZIL_MCC && t && t.gsmLocationAreaCode : null;
	},
	getMobileInfo: function () {
		return this.MOBILE_INFO;
	},
};

export default n129;
